apiVersion: apps/v1
kind: Deployment
metadata:
  name: team1-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: team1-app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: team1-app
    spec:
      containers:
      - name: team1-app-container
        image: 
        ports:
          - protocol: TCP
            containerPort: 8080
