apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vinyl-app-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    # SSL/TLS를 위한 cert-manager 또는 ACM 통합 어노테이션 추가 필요
    # cert-manager.io/cluster-issuer: "letsencrypt-prod" # 예시
    # alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:ap-northeast-2:123456789012:certificate/xxxx" # ACM 사용 시
spec:
  ingressClassName: nginx
  rules:
  - host: www.r53-kjh.shop
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vinyl-app-service
            port:
              number: 8080
  - host: vinyl.r53-kjh.shop
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vinyl-app-service
            port:
              number: 8080
  - host: argocd.r53-kjh.shop
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server # ArgoCD UI 서비스 이름 (기본값)
            port:
              number: 8080 # ArgoCD UI 서비스 포트 (기본값, HTTPS는 443)