apiVersion: v1
kind: Service   
metadata:
  name: vinyl-app-service
  labels:
    app: vinyl-app
spec:
  selector:
    app.kubernetes.io/name: vinyl-app
  #type: ClusterIP
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30080
