apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- service-account.yaml # service account 리소스 참조

images:
- name: h6bro/vinyl-app-repo
  newTag: 123456
#- name: 398563707131.dkr.ecr.ap-northeast-2.amazonaws.com/vinyl-groove # ECR 버전
#  newTag: 0c1469a # ECR 버전
  
namespace: dev
