apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: 398563707131.dkr.ecr.ap-northeast-2.amazonaws.com/vinyl-groove
  newTag: 0c1469a
  
namespace: dev
